=== hamzees/EpamTraining/by.skakun.gemsXML/build/classes/resources/gem.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://wwww.example.com/gemstones"
        xmlns:tns="http://wwww.example.com/gemstones"
        elementFormDefault="qualified">
    
    <element name="gem" type="tns:Gem" abstract="true"></element>
    <element name="semipreciousgem" type="tns:SemiPreciousGem" substitutionGroup="tns:gem"></element>
    <element name="preciousgem" type="tns:PreciousGem" abstract="true" substitutionGroup="tns:gem"></element>
    <element name="realpreciousgem" type="tns:RealPreciousGem" substitutionGroup="tns:preciousgem"></element>
    <element name="artificialgem" type="tns:ArtificialGem" substitutionGroup="tns:preciousgem"></element>


    <element name="necklace">
        <complexType>
            <sequence>
                <element ref = "tns:gem" minOccurs = "1" maxOccurs = "unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Gem">
        <sequence>            
            <element name = "toughness">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="hard"/>
                        <enumeration value="soft"/>
                        <enumeration value="medium"/>
                    </restriction>
                </simpleType>
            </element>   
            <element name = "opacity" type = "positiveInteger" />
            <element name = "weight" type = "positiveInteger" />
            <element name = "cost" type = "positiveInteger" />
            <element name = "name" type = "string"  />
            <element name = "color" type = "string" />   
        </sequence>
        <attribute name = "id" use="required" >
            <simpleType>
                <restriction base="ID">
                    <pattern value = "(^[a-z]{3}\d{2}-\d{7}-[A-Z]{2})" />
                </restriction>
            </simpleType>
        </attribute>
        
    </complexType>
   
    <complexType name="SemiPreciousGem">
        <complexContent>
            <extension base="tns:Gem">
                <sequence>
                    <element name="symbol" type="string" />
                </sequence>    
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="PreciousGem">
        <complexContent>
            <extension base="tns:Gem">
                <sequence>
                    <element name="tougnhess" type="positiveInteger"/>
                    <element name="cutMethod" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="RealPreciousGem">
        <complexContent>
            <extension base="tns:PreciousGem">
                <sequence>
                    <element name="fieldOrigin" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="ArtificialGem">
        <complexContent>
            <extension base="tns:PreciousGem">
                <sequence minOccurs="1" maxOccurs="unbounded">
                    <element name="age" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
</schema>

=== hamzees/EpamTraining/by.skakun.gemsXML/src/resources/necklace.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<necklace
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://wwww.example.com/gem"
    xsi:schemaLocation="http://www.example.com/gem gem.xsd" >
    
    <!--<necklace>   --> 
    <realpreciousgem id="dhw42-8371042-NS">
        <name>бриллиант</name>
        <color>розовый</color>
        <toughness>hard</toughness>
        <cutMethod>круглый</cutMethod>
        <cost>200</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <fieldOrigin>Германия</fieldOrigin>
    </realpreciousgem>
    <artificialgem id="dfg11-9274812-KL">
        <name>сапфир</name>
        <color>синий</color>
        <toughness>soft</toughness>
        <cutMethod>капельная</cutMethod>
        <cost>150</cost>
        <weight>3</weight>
        <opacity>2</opacity>
        <age>5</age>
    </artificialgem>
    <semipreciousgem id="asf12-6392963-LL">
        <name>опал</name>
        <color>белый</color>
        <cost>50</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <symbol>сострадание</symbol>
    </semipreciousgem>
    <!--    </necklace>  -->
</necklace>

=== hamzees/EpamTraining/by.skakun.gemswebxml/src/java/resources/necklace.xml
<?xml version="1.0" encoding="UTF-8" ?>

<necklace
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http:www.example.com/necklace"
    xsi:schemaLocation="http:www.example.com/necklace gem.xsd">
    
    <realpreciousgem id="dhw42-8371042-NS">
        <name>бриллиант</name>
        <color>розовый</color>
        <toughness>hard</toughness>
        <cutMethod>круглый</cutMethod>
        <cost>200</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <fieldOrigin>Германия</fieldOrigin>
    </realpreciousgem>
    <artificialgem id="dfg11-9274812-KL">
        <name>сапфир</name>
        <color>синий</color>
        <toughness>soft</toughness>
        <cutMethod>капельная</cutMethod>
        <cost>150</cost>
        <weight>3</weight>
        <opacity>2</opacity>
        <age>5</age>
    </artificialgem>
    <semipreciousgem id="asf12-6392963-LL">
        <name>опал</name>
        <color>белый</color>
        <cost>50</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <symbol>сострадание</symbol>
    </semipreciousgem>
    <realpreciousgem id="dhw42-8371042-NS">
        <name>бриллиант</name>
        <color>розовый</color>
        <toughness>hard</toughness>
        <cutMethod>круглый</cutMethod>
        <cost>200</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <fieldOrigin>Германия</fieldOrigin>
    </realpreciousgem>
    <artificialgem id="dfg11-9274812-KP">
        <name>сапфир</name>
        <color>синий</color>
        <toughness>soft</toughness>
        <cutMethod>капельная</cutMethod>
        <cost>150</cost>
        <weight>3</weight>
        <opacity>2</opacity>
        <age>5</age>
    </artificialgem>
    <semipreciousgem id="asf12-6392963-BL">
        <name>опал</name>
        <color>белый</color>
        <cost>50</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <symbol>сострадание</symbol>
    </semipreciousgem>
    <realpreciousgem id="dhw42-8371042-XS">
        <name>бриллиант</name>
        <color>розовый</color>
        <toughness>hard</toughness>
        <cutMethod>круглый</cutMethod>
        <cost>200</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <fieldOrigin>Германия</fieldOrigin>
    </realpreciousgem>
    <artificialgem id="dfg11-9274812-KP">
        <name>сапфир</name>
        <color>синий</color>
        <toughness>soft</toughness>
        <cutMethod>капельная</cutMethod>
        <cost>150</cost>
        <weight>3</weight>
        <opacity>2</opacity>
        <age>5</age>
    </artificialgem>
    <semipreciousgem id="asf12-6392963-LC">
        <name>опал</name>
        <color>белый</color>
        <cost>50</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <symbol>сострадание</symbol>
    </semipreciousgem>
    <realpreciousgem id="dhw42-8371042-OS">
        <name>бриллиант</name>
        <color>розовый</color>
        <toughness>hard</toughness>
        <cutMethod>круглый</cutMethod>
        <cost>200</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <fieldOrigin>Германия</fieldOrigin>
    </realpreciousgem>
    <artificialgem id="dfg11-9274812-KA">
        <name>сапфир</name>
        <color>синий</color>
        <toughness>soft</toughness>
        <cutMethod>капельная</cutMethod>
        <cost>250</cost>
        <weight>3</weight>
        <opacity>2</opacity>
        <age>5</age>
    </artificialgem>
    <semipreciousgem id="asf12-6392963-ML">
        <name>опал</name>
        <color>белый</color>
        <cost>150</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <symbol>сострадание</symbol>
    </semipreciousgem>
    <realpreciousgem id="dhw42-8371042-NK">
        <name>бриллиант</name>
        <color>розовый</color>
        <toughness>hard</toughness>
        <cutMethod>круглый</cutMethod>
        <cost>300</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <fieldOrigin>Германия</fieldOrigin>
    </realpreciousgem>
    <artificialgem id="dfg11-9274812-KM">
        <name>сапфир</name>
        <color>синий</color>
        <toughness>soft</toughness>
        <cutMethod>капельная</cutMethod>
        <cost>450</cost>
        <weight>3</weight>
        <opacity>2</opacity>
        <age>5</age>
    </artificialgem>
    <semipreciousgem id="asf12-6392963-LS">
        <name>опал</name>
        <color>белый</color>
        <cost>120</cost>
        <weight>4</weight>
        <opacity>1</opacity>
        <symbol>сострадание</symbol>
    </semipreciousgem>
</necklace>
